Leave module loaded state as it was
eproxus/meck pull request #228
Opened 2021-03-15 16:09 UTC by zsoci

2021-03-18 12:22 UTC, eproxus commented
Do you think you can add tests for this? Ideally one test with a loaded module and one with an unloaded module.

2021-03-18 18:50 UTC, zsoci commented
> Do you think you can add tests for this? Ideally one test with a loaded module and one with an unloaded module.

Do you mean in addition to the cases that already provide full coverage for the added code?
![Screen Shot 2021-03-18 at 7 47 54 PM](https://user-images.githubusercontent.com/8074316/111680998-199ec300-8823-11eb-9a3b-edd48853a26d.png)

2021-03-23 12:47 UTC, eproxus commented
I think those tests are only implicitly loading the module by running cover? Not sure if there's a test that is equivalent to:

1. load module
2. mock module
3. unload mock
4. check that module is re-loaded (without calling the actual module)

Might be wrong though...

2021-03-23 16:26 UTC, zsoci commented
Yes you are right, I think no tests performs step 4. I will create one.

2021-03-25 13:36 UTC, eproxus requested changes

2021-03-25 13:36 UTC, eproxus commented on test/meck_tests.erl
> +    ?assertNotEqual(false, code:is_loaded(meck_test_module)),
Can you change this to `?assertMatch({file, _}, code:is_loaded(meck_test_module)),`?

2021-03-25 13:36 UTC, eproxus commented on src/meck_proc.erl
> +            _ = code:load_file(Mod),
Can you add this comment before the call to `code:load_file/1`?
```
            % We make a best effort to reload the module here. Since this runs
            % in a terminating process there is nothing we can do to recover if
            % the loading fails.
```

2021-03-25 15:03 UTC, zsoci commented on test/meck_tests.erl
> +    ?assertNotEqual(false, code:is_loaded(meck_test_module)),
Done. I did not find assertMatch around the line so tried to comply to assertEqual style ;)

2021-03-25 15:03 UTC, zsoci commented on src/meck_proc.erl
> +            _ = code:load_file(Mod),
Thanks for the good reasoning. Done

2021-03-25 15:05 UTC, eproxus commented on test/meck_tests.erl
> +    ?assertNotEqual(false, code:is_loaded(meck_test_module)),
Yeah, unfortunately `code:is_loaded/1` does not return a boolean 😄 Otherwise `?assert(not code:is_loaded(...))` would have looked beautiful.

2021-03-25 15:07 UTC, zsoci commented
I think this also fixes #214

2021-03-25 15:09 UTC, eproxus commented
Oh, forgot. One more request. Can you add an entry to `CHANGELOG.md` too under *Unreleased* and squash all commits into one?

2021-03-25 15:14 UTC, zsoci commented
Done.

2021-03-25 15:23 UTC, eproxus commented on CHANGELOG.md
> +- Leave module loaded state as it was [\#228](https://github.com/eproxus/meck/pull/228)
Last minor nitpick. This should be under a `### Added` heading. Otherwise looks good!

2021-03-25 15:33 UTC, zsoci commented on CHANGELOG.md
> +- Leave module loaded state as it was [\#228](https://github.com/eproxus/meck/pull/228)
Corrected. Thanks for the clarification. IMO it could also be under Fixed #214

2021-03-25 15:33 UTC, eproxus approved these changes

2021-03-25 15:37 UTC, merged

2021-03-25 15:38 UTC, eproxus commented
Thanks so much! ❤️

2021-03-25 15:40 UTC, eproxus commented on CHANGELOG.md
> +- Leave module loaded state as it was [\#228](https://github.com/eproxus/meck/pull/228)
True, but I feel it is more appropriate to label it as new behavior since it changes the behavior of Meck. It also happens to fix an old issue. 🙂